// <auto-generated />
using System;
using Craqudos.Repositorio.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Craqudos.Repositorio.Migrations
{
    [DbContext(typeof(CraqudosContext))]
    partial class CraqudosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Craqudos.Dominio.Entidades.Equipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataSorteio");

                    b.Property<int>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("NivelAtaque");

                    b.Property<int>("NivelDefesa");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("NomeArquivo");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("UsuarioId");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.JogadorEquipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("EquipeId");

                    b.Property<int>("JogadorId");

                    b.HasKey("Id");

                    b.HasIndex("EquipeId");

                    b.ToTable("JogadoresEquipe");
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Administrador");

                    b.Property<bool>("ContarGoleiro");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("QuantidadeJogadores");

                    b.Property<string>("Senha")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.Equipe", b =>
                {
                    b.HasOne("Craqudos.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany("Equipes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.Jogador", b =>
                {
                    b.HasOne("Craqudos.Dominio.Entidades.Usuario")
                        .WithMany("Jogadores")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Craqudos.Dominio.Entidades.JogadorEquipe", b =>
                {
                    b.HasOne("Craqudos.Dominio.Entidades.Equipe")
                        .WithMany("JogadoresEquipe")
                        .HasForeignKey("EquipeId");
                });
#pragma warning restore 612, 618
        }
    }
}
